import { AddItem } from 'components/listPage/addItem';
import { Filter } from 'components/listPage/filter';
import { Items } from 'components/listPage/items';
import { Metadata } from 'components/listPage/metadata';
import { SiteHeader } from 'components/siteHeader';
import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import { getCurrentUser, getItemsForList, getList } from 'server/db';
import { ListPageInitialState } from 'types/listPage/hydration';

function TodoPage({ list }: ListPageInitialState) {
  return (
    <div>
      <Head>
        <title>{list.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SiteHeader />
      <div className="container">
        <Metadata />
        <AddItem />
        <Filter />
        <Items />
        <style jsx>{`
          .container {
            padding: 0px 20px;
          }
        `}</style>
      </div>
    </div>
  );
}

export default TodoPage;

export const getServerSideProps: GetServerSideProps<
  ListPageInitialState
> = async (context) => {
  const list = await getList(parseInt(context.query.id as string, 10));
  if (!list) {
    return {
      notFound: true,
    };
  }
  const items = await getItemsForList(list.id);
  const currentUser = await getCurrentUser();
  const props: ListPageInitialState = {
    list,
    items,
    currentUser,
  };
  return { props };
};
