import { ItemList } from 'components/todo/itemList'
import { Metadata } from 'components/todo/metadata'
import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import { getList } from 'server/db'
import { DetailedList } from 'types'

interface TodoPageProps {
    list: DetailedList
}

const TodoPage: NextPage<TodoPageProps> = ({ list }: TodoPageProps) => (
    <div>
        <Head>
            <title>Todo {list.id}</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Metadata list={list} />
        <ItemList list={list} />
    </div>
)

export default TodoPage

export const getServerSideProps: GetServerSideProps<
    TodoPageProps
> = async context => {
    const list = await getList(parseInt(context.query.id as string, 10))
    if (!list) {
        return {
            notFound: true,
        }
    }
    return {
        props: {
            list,
        },
    }
}
