import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'

interface TodoPageProps {
    id: number
}

const TodoPage: NextPage<TodoPageProps> = (props: TodoPageProps) => (
    <div>
        <Head>
            <title>Todo {props.id}</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        TODO
    </div>
)

// eslint-disable-next-line @typescript-eslint/require-await
export const getServerSideProps: GetServerSideProps = async context => {
    const id = context.query.id
    return {
        props: {
            id,
        },
    }
}

export default TodoPage
